export const Assets = {
  Backgrounds: {
    Game: 'gameBackground',
    Play: 'playBackground',
    Finish: 'finishBackground',
    Sky: 'sky',
    Clouds: 'clouds',
    Racetrack: 'racetrack',
  },
  Logos: {
    ActiveParents: 'activeParentsLogo',
  },
  Buttons: {
    LetsPlay: 'letsPlayButton',
    Start: 'startButton',
    Done: 'doneButton',
    BlueA: 'blueA',
    BlueB: 'blueB',
    BlueC: 'blueC',
    RedA: 'redA',
    RedB: 'redB',
    RedC: 'redC',
  },
  Avatars: {
    Boy: 'avatarBoy',
    Girl: 'avatarGirl',
    BoyGrey: 'avatarBoyGrey',
    GirlGrey: 'avatarGirlGrey',
    RunBoy: 'runBoy',
    RunGirl: 'runGirl',
    CelebrateBoy: 'avatarCelebrateBoy',
    CelebrateGirl: 'avatarCelebrateGirl',
  },
  UI: {
    GameTitle: 'gameTitle',
    Modal: 'modalBackground',
    QuestionBox: 'questionBoxBackground',
    Track: 'racetrack',
    LaneOptions: 'laneOptions',
    Header: 'chooseAvatarHeader',
    TimerBar: 'timerBar',
    TimerBarInner: 'timerBarInner',
    TimerBarIcon: 'timerBarIcon',
    Analysis1: 'game-analysis1',
    Analysis2: 'game-analysis2',
    Analysis3: 'game-analysis3',
  },
  Countdown: {
    Count1 : 'count1',
    Count2 : 'count2',
    Count3 : 'count3',
    CountGo : 'countGo',
  },
  Animations: {
    Confetti: 'confetti',
  },
};
