export const Assets = {
  Backgrounds: {
    Game: 'gameBackground',
    Play: 'playBackground',
    Finish: 'finishBackground',
    Sky: 'sky',
    Clouds: 'clouds',
    Racetrack: 'racetrack',
    FinishLine: 'finishLine',
    IntroChar: 'introChar',
  },
  Logos: {
    ActiveParents: 'activeParents',
    ActiveParentsWhite: 'activeParentsWhite',
  },
  Buttons: {
    LetsPlay: 'letsPlayButton',
    Start: 'startButton',
    Done: 'doneButton',
    BlueA: 'blueA',
    BlueB: 'blueB',
    BlueC: 'blueC',
    RedA: 'redA',
    RedB: 'redB',
    RedC: 'redC',
  },
  Avatars: {
    Boy: 'avatarBoy',
    Girl: 'avatarGirl',
    BoyGrey: 'avatarBoyGrey',
    GirlGrey: 'avatarGirlGrey',
    RunBoy: 'runBoy',
    StopBoy: 'stopBoy',
    RunGirl: 'runGirl',
    StopGirl: 'stopGirl',
    CelebrateBoy: 'avatarCelebrateBoy',
    CelebrateGirl: 'avatarCelebrateGirl',
  },
  Parents: {
    Sprite: 'sprite',
  },
  UI: {
    GameTitle: 'gameTitle',
    Modal: 'modalBackground',
    QuestionBox: 'questionBoxBackground',
    Track: 'racetrack',
    LaneOptions: 'laneOptions',
    Header: 'chooseAvatarHeader',
    TimerBar: 'timerBar',
    TimerBarInner: 'timerBarInner',
    TimerBarIcon: 'timerBarIcon',
    Analysis1: 'gameAnalysis1',
    Analysis2: 'gameAnalysis2',
    Analysis3: 'gameAnalysis3',
    FlagLeft: 'flagLeft',
    FlagRight: 'flagRight',
    LaneHighlight0: 'lanehighlight0',
    LaneHighlight1: 'lanehighlight1',
    LaneHighlight2: 'lanehighlight2',
  },
  Countdown: {
    Count1 : 'count1',
    Count2 : 'count2',
    Count3 : 'count3',
    CountGo : 'countGo',
  },
  Animations: {
    Confetti: 'confetti',
    RibbonLeft: 'ribbonLeft',
    RibbonRight: 'ribbonRight',
  },
};
